### ISSUE TITLE
missing .ssh home directories deletion

### ISSUE THREAD

**Issue by xiaosal** [DanHam/packer-virt-sysprep#2]
Hi, the .ssh folder under root and users home directories are not deleted. In this way known_hosts and auth_key are not cleaned and remain inside all VMs.

**Comment by DanHam** [comment]
Hi xiaosal. 

Thanks for opening an issue. However, leaving the .ssh folder and it's contents alone is the intended behaviour. 

Generally, adding a users public key to .ssh/authorized_keys is the preferred way to preconfigure or 'bake in' user access for a machine built with Packer. This is especially true when building a Vagrant box for use locally with Virtualbox or VMware Desktop/Fusion or when building some cloud instances. It's for this reason there is no script to delete any existing .ssh directories.

As things stand this is the way I would prefer to leave things. Introducing such a script would most likely introduce complications for people e.g. most builds would need to change the order in which the user creation scripts were run or would need to skip *just* the 'remove .ssh directories' script. At the moment (at least in terms of Packer builds) the scripts provide a sane set of defaults.

Please feel free to reopen if you have any futher questions or points to make.
