### ISSUE TITLE
Criteria for new removal scripts?

### ISSUE THREAD

**Issue by zofrex** [DanHam/packer-virt-sysprep#8]
Hi Dan,

First of all a huge and overdue thank you for this repository, it has saved me from _so many_ VM build problems over the years!

I was wondering what your inclusion criteria are for adding new cleaning scripts. Would you prefer to stick only to software that's included in typical installs, or would you be open to adding scripts for cleaning up commonly used third-party software, where it's possible to shoot yourself in the foot if you clone its configuration?

Specifically I was wondering about adding something to clean up Tailscale keys, as I've seen a few people cause themselves problems by cloning VMs with it already set up — much like SSH, having two machines with the same key is a problem.

**Comment by DanHam** [comment]
Hi @zofrex,

Thank you! I'm glad you've found these scripts useful.

The scripts in this repo were never really intended for doing anything other than cleaning OS based config files / caches and keys. 

If we had started adding scripts for specific cloud providers or services I think things might have gotten a little out of hand!

My advice would be to take a fork and add the clean up scripts for Tailscale there.
